name: learn-github-actions
on:
  pull_request:
    types:
      - closed
env:
  pj_name: blocklist
  funcurl: https://devsl-api.bitkinetic.com/api/v2/block/up
jobs:
  update-blocklist:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: update blocklist
        shell: bash
        run: |
          echo "======${{ github.workspace }}======"
          git clone https://github.com/zhouzhg/blocklist.git
          [ -f ${{ env.pj_name }}/blocklist.sh ] && echo true || echo false
          bash -x ${{ env.pj_name }}/blocklist.sh
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
